# Site settings
title: WildLeoKnight
tagline: Computer Science Engineer, Pixel Artist, Game Dev
description: Portfolio
image: /assets/images/image.png
url: https://wildleoknight.github.io/
sidebar_main_text: 
home_url: /portfolio/
cover_text: Check my website
author: WildLeoKnight
lang: en-US
google_analytics: G-0R3J0WP4Y3
logo: /favicon.ico
twitter:
  username: wildleoknight
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: assets/images/image.png

# Build settings
remote_theme: wildleoknight/stardust 
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap